name: Basic PHP CI/CD Task Automation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Composer dependencies
        uses: actions/cache@v3
        run: cd ./phpcs && composer install
        if: steps.cache-packages.outputs.cache-hit != 'true'

      - name: Running PHPCS
        run: |
          cd phpcs
          sh ./simple-check.sh
      # - name: Completation Text
      #   run: echo "Hello World 3"
