name: Basic PHPCS CI/CD Task Automation
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Clone Marketplace PHPCS Repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'hrrarya'
          repository: 'marketplace-phpcs'

      - name: Install Composer dependencies
        run: |
          cd ./marketplace-phpcs 
          composer install

      - name: Running PHPCS
        run: |
          cd marketplace-phpcs
          sh ./simple-check.sh
