name: Basic PHP CI/CD Task Automation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: cd ./phpcs && composer install

  PHPCS:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Running PHPCS
        run: bash ./simple-check.sh
        workingDirectory: ./phpcs

      # - name: Completation Text
      #   run: echo "Hello World 3"
